name: Update MetaMask Chrome

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--require ''"
      BROWSERIFY_SHIM_DISABLE_LAVAMOAT: 1
      INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone MetaMask extension (shallow)
        run: |
          git clone --depth=1 https://github.com/MetaMask/metamask-extension.git tmp-metamask

      - name: Set up correct Yarn
        run: |
          cd tmp-metamask
          corepack enable
          yarn set version from sources

      - name: Install dependencies
        run: |
          cd tmp-metamask
          yarn install

      - name: Configure .metamaskrc
        run: |
          cp .metamaskrc{.dist,}
          sed -i "s/^INFURA_PROJECT_ID=.*/INFURA_PROJECT_ID=${INFURA_PROJECT_ID}/" .metamaskrc
        working-directory: tmp-metamask

      - name: Build Chrome dist
        run: |
          cd tmp-metamask
          yarn dist --apply-lavamoat=false

      - name: Copy built dist/chrome to repo
        run: |
          rm -rf dist && mkdir dist
          cp -r tmp-metamask/dist/chrome/. dist/

      - name: Clean up temp clone
        run: rm -rf tmp-metamask

      - name: Create and push branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git checkout -b update-metamask-${{ github.run_id }}
          git add dist/
          git commit -m "Update MetaMask Chrome dist"
          git push origin update-metamask-${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-metamask-${{ github.run_id }}
          base: main
          title: "Update MetaMask dist files"
          body: |
            This PR updates the Chrome dist files from MetaMask.
            Triggered by GitHub Actions.
