name: Update MetaMask Extension

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 1 * *' # Uncomment to run monthly on the 1st at 00:00 UTC

jobs:
  update-metamask:
    runs-on: ubuntu-latest
    env:
      BROWSERIFY_SHIM_DISABLE_LAVAMOAT: 1

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install Corepack and enable it
        run: |
          corepack enable

      - name: Clone MetaMask repo
        run: |
          git clone https://github.com/MetaMask/metamask-extension.git

      - name: Set Yarn version from MetaMask package.json
        run: |
          cd metamask-extension
          corepack enable
          yarn set version 4.7.0

      - name: Install dependencies
        run: |
          cd metamask-extension
          yarn install

      - name: Configure .metamaskrc with Infura Project ID
        run: |
          cp .metamaskrc{.dist,}
          sed -i "s/^INFURA_PROJECT_ID=.*/INFURA_PROJECT_ID=${INFURA_PROJECT_ID}/" .metamaskrc
        working-directory: metamask-extension
        env:
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}

      - name: Build MetaMask
        run: |
          cd metamask-extension
          yarn dist --apply-lavamoat=false



      - name: Copy built files to this repo
        run: |
          rm -rf dist && mkdir dist
          cp -r metamask-extension/dist/chrome/* dist/

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Update MetaMask dist files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
