name: Update MetaMask Chrome

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'   # monthly, 00:00 UTC on the 1st

# ✅ critical: let the bot push & open PRs
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BROWSERIFY_SHIM_DISABLE_LAVAMOAT: 1
      INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone MetaMask extension (shallow)
        run: git clone --depth=1 https://github.com/MetaMask/metamask-extension.git tmp-metamask

      - name: Set up correct Yarn
        working-directory: tmp-metamask
        run: |
          corepack enable
          yarn set version 4.9.1

      - name: Install dependencies
        working-directory: tmp-metamask
        run: yarn install

      - name: Configure .metamaskrc
        working-directory: tmp-metamask
        run: |
          cp .metamaskrc{.dist,}
          sed -i "s/^INFURA_PROJECT_ID=.*/INFURA_PROJECT_ID=${INFURA_PROJECT_ID}/" .metamaskrc

      - name: Build Chrome dist
        working-directory: tmp-metamask
        run: yarn dist --apply-lavamoat=false

      - name: Copy built dist/chrome to repo
        run: |
          rm -rf dist && mkdir dist
          cp -r tmp-metamask/dist/chrome/. dist/

      - name: Clean up temp clone
        run: rm -rf tmp-metamask

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # either is fine; this one is the canonical context
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update MetaMask Chrome dist"
          branch: update-metamask-${{ github.run_id }}
          base: main
          title: "Update MetaMask dist files"
          body: |
            This PR updates the Chrome dist files from MetaMask.
            Triggered by GitHub Actions.
          add-paths: |
            dist/**
          # Optional but helps with branch rules requiring a known committer
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
